package com.photonicomega.facilities.module.legal.domain;

import com.photonicomega.facilities.common.domain.BaseEntity;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * A stateful, actionable legal notice for the Legal Officer. Generated by
 * scanning contracts (pending review, expiring, expired, renewal due),
 * high-risk contract clauses, and legal cases (hearings due, high priority).
 * Deduplicated by {@code dedupKey} so regeneration never creates duplicate
 * rows and preserves acknowledge/dismiss state across regenerations.
 */
@Entity
@Table(name = "legal_notices")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LegalNotice extends BaseEntity {

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NoticeType type;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NoticeSeverity severity;

    @Column(nullable = false)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String message;

    private String entityType;

    private String entityId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private NoticeStatus status;

    @Column(unique = true)
    private String dedupKey;

    private String acknowledgedBy;

    private LocalDateTime acknowledgedAt;
}
