package com.photonicomega.facilities.module.compliance.domain;

import com.photonicomega.facilities.common.domain.BaseEntity;
import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

/**
 * A stateful, actionable compliance alert. Generated by scanning contracts,
 * documents, and disposal requests; deduplicated by {@code dedupKey} so
 * regeneration never creates duplicate rows and preserves acknowledge/dismiss
 * state across regenerations.
 */
@Entity
@Table(name = "compliance_alerts")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class ComplianceAlert extends BaseEntity {

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AlertType type;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AlertSeverity severity;

    @Column(nullable = false)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String message;

    private String entityType;

    private String entityId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private AlertStatus status;

    @Column(unique = true)
    private String dedupKey;

    private String acknowledgedBy;

    private LocalDateTime acknowledgedAt;
}
